version: 2.1
jobs:
  build_image:
    docker:
      - image: circleci/node:12.22.0
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          IMAGE=x3enos/time_tracker_front:$CIRCLE_SHA1
          DEVELOPMENT=x3enos/time_tracker_front:$CIRCLE_SHA1
          docker build -t $IMAGE -t $DEVELOPMENT .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $IMAGE
          docker push $DEVELOPMENT
  build:
    docker:
      - image: circleci/node:12.10.0

    working_directory: ~/time_tracker_front

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: install yarn dependences
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: test
          command: npm run test
  deploy_staging:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: |
          curl -u $CATTLE_KEY \
          -X POST \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          'https://k8s.andres-sild.com/v3/project/c-r9l2h:p-cnhjm/workloads/deployment:staging:time-tracker-front?action=redeploy'
  deploy_production:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: |
          curl -u $CATTLE_KEY \
          -X POST \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          'https://k8s.andres-sild.com/v3/project/c-r9l2h:p-cnhjm/workloads/deployment:staging:time-tracker-front-production?action=redeploy'

workflows:
  build_and_deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - /TT-.*/
              - master
      - build_image:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_staging_approval:
          name: Deploy to staging
          type: approval
          requires:
            - build_image
          filters:
            branches:
              only: master
      - deploy_staging:
          requires:
            - Deploy to staging
          filters:
            branches:
              only: master
      - deploy_production_approval:
          name: Deploy to production
          type: approval
          requires:
            - build_image
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - Deploy to production
          filters:
            branches:
              only: master
