const TIMEZONES = {
  "International Date Line West": "International Date Line West - GMT-12",
  "American Samoa": "American Samoa - GMT-11",
  "Midway Island": "Midway Island - GMT-11",
  "Hawaii": "Hawaii - GMT-10",
  "Alaska": "Alaska - GMT-9",
  "Pacific Time (US & Canada)": "Pacific Time (US & Canada) - GMT-8",
  "Tijuana": "Tijuana - GMT-8",
  "Arizona": "Arizona - GMT-7",
  "Chihuahua": "Chihuahua - GMT-7",
  "Mazatlan": "Mazatlan - GMT-7",
  "Mountain Time (US & Canada)": "Mountain Time (US & Canada) - GMT-7",
  "Central America": "Central America - GMT-6",
  "Central Time (US & Canada)": "Central Time (US & Canada) - GMT-6",
  "Guadalajara": "Guadalajara - GMT-6",
  "Mexico City": "Mexico City - GMT-6",
  "Monterrey": "Monterrey - GMT-6",
  "Saskatchewan": "Saskatchewan - GMT-6",
  "Bogota": "Bogota - GMT-5",
  "Eastern Time (US & Canada)": "Eastern Time (US & Canada) - GMT-5",
  "Indiana (East)": "Indiana (East) - GMT-5",
  "Lima": "Lima - GMT-5",
  "Quito": "Quito - GMT-5",
  "Atlantic Time (Canada)": "Atlantic Time (Canada) - GMT-4",
  "Caracas": "Caracas - GMT-4",
  "Georgetown": "Georgetown - GMT-4",
  "La Paz": "La Paz - GMT-4",
  "Puerto Rico": "Puerto Rico - GMT-4",
  "Santiago": "Santiago - GMT-4",
  "Newfoundland": "Newfoundland - GMT-4",
  "Brasilia": "Brasilia - GMT-3",
  "Buenos Aires": "Buenos Aires - GMT-3",
  "Greenland": "Greenland - GMT-3",
  "Montevideo": "Montevideo - GMT-3",
  "Mid-Atlantic": "Mid-Atlantic - GMT-2",
  "Azores": "Azores - GMT-1",
  "Cape Verde Is.": "Cape Verde Is. - GMT-1",
  "Edinburgh": "Edinburgh - GMT+0",
  "Lisbon": "Lisbon - GMT+0",
  "London": "London - GMT+0",
  "Monrovia": "Monrovia - GMT+0",
  "UTC": "UTC - GMT+0",
  "Amsterdam": "Amsterdam - GMT+1",
  "Belgrade": "Belgrade - GMT+1",
  "Berlin": "Berlin - GMT+1",
  "Bern": "Bern - GMT+1",
  "Bratislava": "Bratislava - GMT+1",
  "Brussels": "Brussels - GMT+1",
  "Budapest": "Budapest - GMT+1",
  "Casablanca": "Casablanca - GMT+1",
  "Copenhagen": "Copenhagen - GMT+1",
  "Dublin": "Dublin - GMT+1",
  "Ljubljana": "Ljubljana - GMT+1",
  "Madrid": "Madrid - GMT+1",
  "Paris": "Paris - GMT+1",
  "Prague": "Prague - GMT+1",
  "Rome": "Rome - GMT+1",
  "Sarajevo": "Sarajevo - GMT+1",
  "Skopje": "Skopje - GMT+1",
  "Stockholm": "Stockholm - GMT+1",
  "Vienna": "Vienna - GMT+1",
  "Warsaw": "Warsaw - GMT+1",
  "West Central Africa": "West Central Africa - GMT+1",
  "Zagreb": "Zagreb - GMT+1",
  "Zurich": "Zurich - GMT+1",
  "Athens": "Athens - GMT+2",
  "Bucharest": "Bucharest - GMT+2",
  "Cairo": "Cairo - GMT+2",
  "Harare": "Harare - GMT+2",
  "Helsinki": "Helsinki - GMT+2",
  "Jerusalem": "Jerusalem - GMT+2",
  "Kaliningrad": "Kaliningrad - GMT+2",
  "Kyiv": "Kyiv - GMT+2",
  "Pretoria": "Pretoria - GMT+2",
  "Riga": "Riga - GMT+2",
  "Sofia": "Sofia - GMT+2",
  "Tallinn": "Tallinn - GMT+2",
  "Vilnius": "Vilnius - GMT+2",
  "Baghdad": "Baghdad - GMT+3",
  "Istanbul": "Istanbul - GMT+3",
  "Kuwait": "Kuwait - GMT+3",
  "Minsk": "Minsk - GMT+3",
  "Moscow": "Moscow - GMT+3",
  "Nairobi": "Nairobi - GMT+3",
  "Riyadh": "Riyadh - GMT+3",
  "St. Petersburg": "St. Petersburg - GMT+3",
  "Tehran": "Tehran - GMT+3",
  "Abu Dhabi": "Abu Dhabi - GMT+4",
  "Baku": "Baku - GMT+4",
  "Muscat": "Muscat - GMT+4",
  "Samara": "Samara - GMT+4",
  "Tbilisi": "Tbilisi - GMT+4",
  "Volgograd": "Volgograd - GMT+4",
  "Yerevan": "Yerevan - GMT+4",
  "Kabul": "Kabul - GMT+4",
  "Ekaterinburg": "Ekaterinburg - GMT+5",
  "Islamabad": "Islamabad - GMT+5",
  "Karachi": "Karachi - GMT+5",
  "Tashkent": "Tashkent - GMT+5",
  "Chennai": "Chennai - GMT+5",
  "Kolkata": "Kolkata - GMT+5",
  "Mumbai": "Mumbai - GMT+5",
  "New Delhi": "New Delhi - GMT+5",
  "Sri Jayawardenepura": "Sri Jayawardenepura - GMT+5",
  "Kathmandu": "Kathmandu - GMT+5",
  "Almaty": "Almaty - GMT+6",
  "Astana": "Astana - GMT+6",
  "Dhaka": "Dhaka - GMT+6",
  "Urumqi": "Urumqi - GMT+6",
  "Rangoon": "Rangoon - GMT+6",
  "Bangkok": "Bangkok - GMT+7",
  "Hanoi": "Hanoi - GMT+7",
  "Jakarta": "Jakarta - GMT+7",
  "Krasnoyarsk": "Krasnoyarsk - GMT+7",
  "Novosibirsk": "Novosibirsk - GMT+7",
  "Beijing": "Beijing - GMT+8",
  "Chongqing": "Chongqing - GMT+8",
  "Hong Kong": "Hong Kong - GMT+8",
  "Irkutsk": "Irkutsk - GMT+8",
  "Kuala Lumpur": "Kuala Lumpur - GMT+8",
  "Perth": "Perth - GMT+8",
  "Singapore": "Singapore - GMT+8",
  "Taipei": "Taipei - GMT+8",
  "Ulaanbaatar": "Ulaanbaatar - GMT+8",
  "Osaka": "Osaka - GMT+9",
  "Sapporo": "Sapporo - GMT+9",
  "Seoul": "Seoul - GMT+9",
  "Tokyo": "Tokyo - GMT+9",
  "Yakutsk": "Yakutsk - GMT+9",
  "Adelaide": "Adelaide - GMT+9",
  "Darwin": "Darwin - GMT+9",
  "Brisbane": "Brisbane - GMT+10",
  "Canberra": "Canberra - GMT+10",
  "Guam": "Guam - GMT+10",
  "Hobart": "Hobart - GMT+10",
  "Melbourne": "Melbourne - GMT+10",
  "Port Moresby": "Port Moresby - GMT+10",
  "Sydney": "Sydney - GMT+10",
  "Vladivostok": "Vladivostok - GMT+10",
  "Magadan": "Magadan - GMT+11",
  "New Caledonia": "New Caledonia - GMT+11",
  "Solomon Is.": "Solomon Is. - GMT+11",
  "Srednekolymsk": "Srednekolymsk - GMT+11",
  "Auckland": "Auckland - GMT+12",
  "Fiji": "Fiji - GMT+12",
  "Kamchatka": "Kamchatka - GMT+12",
  "Marshall Is.": "Marshall Is. - GMT+12",
  "Wellington": "Wellington - GMT+12",
  "Chatham Is.": "Chatham Is. - GMT+12",
  "Nuku'alofa": "Nuku'alofa - GMT+13",
  "Samoa": "Samoa - GMT+13",
  "Tokelau Is.": "Tokelau Is. - GMT+13"
}

 export default {
  TIMEZONES
}
